import type { ActivitiesConfig } from './types.ts';

/**
 * Stadtarbeit (v0.21, § aktives Stadtmanagement): short, repeatable, hands-on
 * mayor tasks that bridge build timers with active play. All values live here —
 * reward bands follow the progression spec: thousands early, tens of thousands
 * mid-game (L6–9), hundreds of thousands from L10, with rare ~1M trade mega
 * contracts. Rewards only ever pay out through controller commands, so none of
 * this can accrue offline.
 */
export const activitiesConfig: ActivitiesConfig = {
  activities: [
    // -- Deliveries: an ordered route run — click the numbered stops in turn.
    //    No cooldown (§2): a delivery is always available while food sources and
    //    homes exist. Speed + completion decide the Bronze/Silber/Gold grade.
    {
      id: 'food_delivery',
      type: 'delivery',
      category: 'supply',
      difficulty: 'easy',
      nameKey: 'activity.food_delivery',
      descriptionKey: 'activity.food_delivery.desc',
      unlockLevel: 4, // as soon as farms exist food can be hand-distributed (§3)
      sender: 'citizen',
      requiresAnyBuilding: ['farm', 'market', 'supermarket'],
      drive: true, // § A6: Lieferwagen selbst fahren (WASD, Verfolgerkamera)
      vehicle: 'van',
      vehicleOptions: ['van', 'refrigerated_truck', 'medium_truck', 'large_truck'],
      targetCount: { min: 3, max: 5 },
      timeLimitSec: 75,
      speedBonusFactor: 1.25,
      costPerTarget: { food: 40 },
      // Transportvolumen (§ Stadtarbeit-Logik 2.0): skaliert mit der Zielgröße,
      // damit größere Wohnziele echte Nachladungen erzwingen — der abstrakte
      // Ökonomie-Verbrauch bleibt bei `costPerTarget`.
      cargoModel: { resource: 'food', perTarget: 60, scaleByResidents: true, perishable: true },
      rewardTiers: [
        { minLevel: 1, money: 4_000, xp: 10, buff: { kind: 'foodDistribution', amount: 1, durationSec: 10 * 60 } },
        { minLevel: 6, money: 16_000, xp: 22, buff: { kind: 'foodDistribution', amount: 1, durationSec: 10 * 60 } },
        { minLevel: 8, money: 42_000, xp: 38, buff: { kind: 'foodDistribution', amount: 1, durationSec: 12 * 60 } },
        { minLevel: 10, money: 130_000, xp: 60, buff: { kind: 'foodDistribution', amount: 1, durationSec: 15 * 60 } },
        { minLevel: 12, money: 300_000, xp: 90, buff: { kind: 'foodDistribution', amount: 1, durationSec: 15 * 60 } },
      ],
    },
    {
      id: 'material_delivery',
      type: 'delivery',
      category: 'supply',
      difficulty: 'medium',
      nameKey: 'activity.material_delivery',
      descriptionKey: 'activity.material_delivery.desc',
      unlockLevel: 7,
      sender: 'buildingDept',
      requiresAnyBuilding: ['sawmill', 'quarry', 'warehouse', 'depot'],
      drive: true, // § A6: Material selbst zur Baustelle fahren (Pritschenwagen)
      vehicle: 'flatbed',
      vehicleOptions: ['flatbed', 'medium_truck', 'large_truck', 'heavy_transporter'],
      targetCount: { min: 3, max: 4 },
      timeLimitSec: 60,
      speedBonusFactor: 1.25,
      costPerTarget: { wood: 30, stone: 15 },
      // Die Wirtschaft verbraucht weiterhin Holz + Stein. Für das physische
      // Fahrzeugvolumen dient Holz als repräsentative Mischladung; ein eigener
      // "Baumaterial"-Resource-Typ wäre eine Save-/Ökonomieänderung.
      cargoModel: { resource: 'wood', perTarget: 90 },
      rewardTiers: [
        { minLevel: 7, money: 26_000, xp: 28 },
        { minLevel: 9, money: 60_000, xp: 45 },
        { minLevel: 11, money: 180_000, xp: 70 },
        { minLevel: 13, money: 380_000, xp: 100 },
      ],
    },
    // -- Trinkwasser: kleine, verderbfreie Versorgungstour. Sie erweitert das
    //    bestehende Delivery-/Cargo-System nur per Config-Eintrag.
    {
      id: 'water_delivery',
      type: 'delivery',
      category: 'supply',
      difficulty: 'medium',
      nameKey: 'activity.water_delivery',
      descriptionKey: 'activity.water_delivery.desc',
      unlockLevel: 7,
      sender: 'citizen',
      requiresAnyBuilding: ['water_pump', 'waterworks'],
      drive: true,
      vehicle: 'van',
      vehicleOptions: ['van', 'medium_truck', 'large_truck'],
      targetCategories: ['residential'],
      targetCount: { min: 3, max: 5 },
      timeLimitSec: 85,
      speedBonusFactor: 1.2,
      costPerTarget: { freshwater: 30 },
      cargoModel: { resource: 'freshwater', perTarget: 75, scaleByResidents: true },
      rewardTiers: [
        { minLevel: 7, money: 22_000, xp: 26 },
        { minLevel: 9, money: 54_000, xp: 42 },
        { minLevel: 11, money: 150_000, xp: 68 },
        { minLevel: 14, money: 340_000, xp: 100 },
      ],
    },
    // -- Feuerwehr (§ A6): mit dem Löschfahrzeug zu mehreren Bränden fahren.
    //    Ziele = bewohnte/gewerbliche Gebäude; kein Materialverbrauch, dafür
    //    knappe Zeit. Setzt eine Feuerwache voraus.
    {
      id: 'fire_response',
      type: 'delivery',
      category: 'safety',
      difficulty: 'hard',
      nameKey: 'activity.fire_response',
      descriptionKey: 'activity.fire_response.desc',
      unlockLevel: 9,
      sender: 'fire',
      requiresAnyBuilding: ['fire_station'],
      drive: true,
      vehicle: 'fire_truck',
      vehicleOptions: ['fire_truck'],
      targetCategories: ['residential', 'economy', 'leisure'],
      targetCount: { min: 3, max: 4 },
      timeLimitSec: 70,
      speedBonusFactor: 1.3,
      rewardTiers: [
        { minLevel: 9, money: 34_000, xp: 40, buff: { kind: 'happiness', amount: 3, durationSec: 10 * 60 } },
        { minLevel: 11, money: 90_000, xp: 60, buff: { kind: 'happiness', amount: 4, durationSec: 12 * 60 } },
        { minLevel: 14, money: 220_000, xp: 90, buff: { kind: 'happiness', amount: 5, durationSec: 15 * 60 } },
        { minLevel: 16, money: 420_000, xp: 130, buff: { kind: 'happiness', amount: 6, durationSec: 15 * 60 } },
      ],
    },
    // -- Holztransport (§ A6): Stämme vom Sägewerk ins Lager fahren. Ziele sind
    //    ausschließlich Lagergebäude (Def-Id-Auswahl), keine Häuser.
    {
      id: 'log_transport',
      type: 'delivery',
      category: 'logistics',
      difficulty: 'medium',
      nameKey: 'activity.log_transport',
      descriptionKey: 'activity.log_transport.desc',
      unlockLevel: 8,
      sender: 'buildingDept',
      requiresAnyBuilding: ['sawmill'],
      drive: true,
      vehicle: 'logging_truck',
      vehicleOptions: ['logging_truck', 'heavy_transporter'],
      targetDefIds: ['warehouse', 'depot'],
      targetCount: { min: 2, max: 3 },
      timeLimitSec: 80,
      speedBonusFactor: 1.25,
      costPerTarget: { wood: 40 },
      cargoModel: { resource: 'wood', perTarget: 140 },
      rewardTiers: [
        { minLevel: 8, money: 30_000, xp: 34 },
        { minLevel: 10, money: 80_000, xp: 55 },
        { minLevel: 13, money: 210_000, xp: 85 },
        { minLevel: 15, money: 420_000, xp: 120 },
      ],
    },
    // -- Markt-Nachschub: empfindliche Ware aus einem echten Lager zu mehreren
    //    Handelszielen. Erzeugt andere Quellen/Ziele als food_delivery.
    {
      id: 'market_restock',
      type: 'delivery',
      category: 'trade',
      difficulty: 'medium',
      nameKey: 'activity.market_restock',
      descriptionKey: 'activity.market_restock.desc',
      unlockLevel: 8,
      sender: 'merchant',
      requiresAnyBuilding: ['warehouse', 'depot'],
      drive: true,
      vehicle: 'refrigerated_truck',
      vehicleOptions: ['van', 'refrigerated_truck', 'medium_truck', 'large_truck'],
      targetDefIds: ['market', 'supermarket', 'trading_post'],
      targetCount: { min: 2, max: 4 },
      timeLimitSec: 80,
      speedBonusFactor: 1.25,
      costPerTarget: { food: 55 },
      cargoModel: { resource: 'food', perTarget: 100, perishable: true },
      rewardTiers: [
        { minLevel: 8, money: 28_000, xp: 30 },
        { minLevel: 10, money: 76_000, xp: 50 },
        { minLevel: 12, money: 210_000, xp: 78 },
        { minLevel: 15, money: 430_000, xp: 118 },
      ],
    },
    // -- Grünflächenpflege: sperrige, nicht verderbliche Ladung vom Bauhof zu
    //    Parks. Visuell Umweltauftrag, technisch dieselbe bewährte Delivery.
    {
      id: 'park_supply',
      type: 'delivery',
      category: 'environment',
      difficulty: 'easy',
      nameKey: 'activity.park_supply',
      descriptionKey: 'activity.park_supply.desc',
      unlockLevel: 8,
      sender: 'buildingDept',
      requiresAnyBuilding: ['warehouse', 'depot'],
      drive: true,
      vehicle: 'flatbed',
      vehicleOptions: ['van', 'flatbed', 'medium_truck'],
      targetDefIds: ['park'],
      targetCount: { min: 2, max: 4 },
      timeLimitSec: 100,
      speedBonusFactor: 1.15,
      costPerTarget: { wood: 25 },
      cargoModel: { resource: 'wood', perTarget: 85 },
      rewardTiers: [
        { minLevel: 8, money: 20_000, xp: 24, buff: { kind: 'happiness', amount: 2, durationSec: 8 * 60 } },
        { minLevel: 10, money: 58_000, xp: 42, buff: { kind: 'happiness', amount: 2, durationSec: 10 * 60 } },
        { minLevel: 12, money: 160_000, xp: 65, buff: { kind: 'happiness', amount: 3, durationSec: 12 * 60 } },
        { minLevel: 15, money: 350_000, xp: 95, buff: { kind: 'happiness', amount: 3, durationSec: 15 * 60 } },
      ],
    },
    // -- Polizei (§ A6): Streifenfahrt zu mehreren Einsatzorten quer durch die
    //    Stadt. Ziele = beliebige größere Gebäude; belohnt Zufriedenheit.
    {
      id: 'police_patrol',
      type: 'delivery',
      category: 'safety',
      difficulty: 'medium',
      nameKey: 'activity.police_patrol',
      descriptionKey: 'activity.police_patrol.desc',
      unlockLevel: 11,
      sender: 'mayor',
      requiresAnyBuilding: ['police_station'],
      drive: true,
      vehicle: 'police_car',
      vehicleOptions: ['police_car'],
      targetCategories: ['residential', 'economy', 'government', 'leisure'],
      targetCount: { min: 4, max: 5 },
      timeLimitSec: 90,
      speedBonusFactor: 1.3,
      rewardTiers: [
        { minLevel: 11, money: 70_000, xp: 55, buff: { kind: 'happiness', amount: 3, durationSec: 12 * 60 } },
        { minLevel: 14, money: 190_000, xp: 85, buff: { kind: 'happiness', amount: 4, durationSec: 15 * 60 } },
        { minLevel: 17, money: 420_000, xp: 130, buff: { kind: 'happiness', amount: 5, durationSec: 15 * 60 } },
      ],
    },
    // -- Inspection: visit flagged buildings, learn what's wrong, get paid.
    //    No cooldown — a new inspection can be run whenever the city has issues.
    {
      id: 'city_inspection',
      type: 'inspection',
      category: 'inspection',
      difficulty: 'medium',
      nameKey: 'activity.city_inspection',
      descriptionKey: 'activity.city_inspection.desc',
      unlockLevel: 6,
      sender: 'mayor',
      targetCount: { min: 3, max: 5 },
      rewardTiers: [
        { minLevel: 6, money: 12_000, xp: 30 },
        { minLevel: 8, money: 30_000, xp: 50 },
        { minLevel: 10, money: 90_000, xp: 75 },
        { minLevel: 12, money: 200_000, xp: 110 },
      ],
    },
    // -- Mayor decisions (§12): 3–4 real options with multi-effect trade-offs.
    //    These keep a modest cooldown so a single policy can't be spam-farmed.
    {
      id: 'decision_farm_subsidy',
      type: 'decision',
      category: 'politics',
      difficulty: 'medium',
      nameKey: 'activity.decision_farm_subsidy',
      descriptionKey: 'activity.decision_farm_subsidy.desc',
      unlockLevel: 6,
      cooldownSec: 15 * 60,
      sender: 'merchant',
      options: [
        {
          id: 'big',
          cost: { money: 40_000 },
          buffs: [
            { kind: 'production', amount: 1.3, durationSec: 10 * 60 },
            { kind: 'happiness', amount: 5, durationSec: 5 * 60 },
          ],
          reward: { xp: 30 },
        },
        { id: 'small', cost: { money: 12_000 }, buffs: [{ kind: 'production', amount: 1.1, durationSec: 10 * 60 }], reward: { xp: 15 } },
        {
          id: 'contract',
          requiresAnyBuilding: ['trading_post'],
          cost: { money: 15_000 },
          buffs: [{ kind: 'production', amount: 1.2, durationSec: 20 * 60 }],
          reward: { xp: 25 },
        },
        { id: 'decline', buffs: [{ kind: 'happiness', amount: -3, durationSec: 8 * 60 }], reward: { money: 5_000, xp: 8 } },
      ],
      rewardTiers: [
        { minLevel: 1, money: 0, xp: 5 },
        { minLevel: 10, money: 0, xp: 15 },
      ],
    },
    {
      id: 'decision_street_party',
      type: 'decision',
      category: 'event',
      difficulty: 'easy',
      nameKey: 'activity.decision_street_party',
      descriptionKey: 'activity.decision_street_party.desc',
      unlockLevel: 7,
      cooldownSec: 15 * 60,
      sender: 'citizen',
      options: [
        { id: 'big', cost: { money: 30_000 }, buffs: [{ kind: 'happiness', amount: 8, durationSec: 20 * 60 }], reward: { xp: 30 } },
        { id: 'small', cost: { money: 10_000 }, buffs: [{ kind: 'happiness', amount: 4, durationSec: 12 * 60 }], reward: { xp: 15 } },
        {
          id: 'sponsor',
          requiresAnyBuilding: ['market', 'supermarket', 'shop_small'],
          cost: { money: 18_000 },
          buffs: [{ kind: 'happiness', amount: 6, durationSec: 15 * 60 }],
          reward: { money: 6_000, xp: 22 },
        },
        { id: 'skip', reward: { money: 8_000, xp: 8 } },
      ],
      rewardTiers: [
        { minLevel: 1, money: 0, xp: 5 },
        { minLevel: 10, money: 0, xp: 15 },
      ],
    },
    {
      id: 'decision_overtime',
      type: 'decision',
      category: 'politics',
      difficulty: 'hard',
      nameKey: 'activity.decision_overtime',
      descriptionKey: 'activity.decision_overtime.desc',
      unlockLevel: 8,
      cooldownSec: 15 * 60,
      sender: 'buildingDept',
      options: [
        { id: 'pay', cost: { money: 60_000 }, buffs: [{ kind: 'production', amount: 1.2, durationSec: 30 * 60 }], reward: { xp: 40 } },
        { id: 'partial', cost: { money: 25_000 }, buffs: [{ kind: 'production', amount: 1.1, durationSec: 20 * 60 }], reward: { xp: 22 } },
        { id: 'refuse', buffs: [{ kind: 'happiness', amount: -6, durationSec: 15 * 60 }], reward: { money: 15_000, xp: 10 } },
      ],
      rewardTiers: [
        { minLevel: 1, money: 0, xp: 5 },
        { minLevel: 11, money: 0, xp: 18 },
      ],
    },
  ],

  // -- Fahrzeugkatalog ---------------------------------------------------------
  // Werte sind kanonische Config-Daten. Renderer und UI lesen nur diese
  // Definitionen; Zukunftsträger bleiben sichtbar, aber nicht auswählbar.
  vehicles: [
    {
      // § P-C Frühlogistik: der Handkarren ist ab Level 2 verfügbar, damit lokal
      // geerntetes Holz vom Sägewerk ins Rathauslager gelangt, BEVOR ein
      // Motorfahrzeug (Lieferwagen, L4) freigeschaltet ist. Kleine Ladung, kein
      // Motor → keine Betriebskosten, langsam. Nur für Lagertransporte relevant
      // (keine Stadtarbeit-Mission listet ihn).
      // Frachtkahn (§ Infrastruktur 2.0 / I4): das Schiff persistenter
      // Schiffsrouten. Große Ladung, langsam, spürbare Betriebskosten je Fahrt —
      // die strategische Gegenrechnung zum kurzen, billigen Landweg. Keine
      // Stadtarbeit-Mission listet ihn (reines Routen-Fahrzeug).
      id: 'cargo_barge',
      nameKey: 'vehicle.cargo_barge',
      descriptionKey: 'vehicle.cargo_barge.desc',
      unlockLevel: 6,
      capacity: 260,
      speedKph: 18,
      handling: 3,
      operatingCost: 900,
      consumption: 'high',
      imageKey: 'cargo_barge',
      strengthsKeys: ['vehicle.strength.capacity', 'vehicle.strength.water'],
      weaknessesKeys: ['vehicle.weakness.slow', 'vehicle.weakness.cost'],
      loadTimeSec: 18,
      unloadTimeSecPerTarget: 14,
      narrowStreetPenalty: 0,
    },
    {
      id: 'handcart',
      nameKey: 'vehicle.handcart',
      descriptionKey: 'vehicle.handcart.desc',
      unlockLevel: 2,
      capacity: 40,
      speedKph: 22,
      handling: 5,
      operatingCost: 0,
      consumption: 'low',
      imageKey: 'handcart',
      strengthsKeys: ['vehicle.strength.short', 'vehicle.strength.cheap'],
      weaknessesKeys: ['vehicle.weakness.capacity', 'vehicle.weakness.slow'],
      loadTimeSec: 8,
      unloadTimeSecPerTarget: 6,
      narrowStreetPenalty: 0,
    },
    {
      id: 'van',
      nameKey: 'vehicle.van',
      descriptionKey: 'vehicle.van.desc',
      unlockLevel: 4,
      capacity: 250,
      speedKph: 80,
      handling: 5,
      operatingCost: 120,
      consumption: 'low',
      imageKey: 'service_van',
      strengthsKeys: ['vehicle.strength.short', 'vehicle.strength.cheap'],
      weaknessesKeys: ['vehicle.weakness.capacity', 'vehicle.weakness.congestion'],
      loadTimeSec: 6,
      unloadTimeSecPerTarget: 4,
      narrowStreetPenalty: 0.05,
    },
    {
      id: 'medium_truck',
      nameKey: 'vehicle.medium_truck',
      descriptionKey: 'vehicle.medium_truck.desc',
      unlockLevel: 7,
      capacity: 500,
      speedKph: 62,
      handling: 4,
      operatingCost: 240,
      consumption: 'medium',
      imageKey: 'medium_truck',
      strengthsKeys: ['vehicle.strength.balance', 'vehicle.strength.medium_routes'],
      weaknessesKeys: ['vehicle.weakness.cost', 'vehicle.weakness.narrow'],
      loadTimeSec: 10,
      unloadTimeSecPerTarget: 5,
      narrowStreetPenalty: 0.15,
    },
    {
      id: 'large_truck',
      nameKey: 'vehicle.large_truck',
      descriptionKey: 'vehicle.large_truck.desc',
      unlockLevel: 12,
      capacity: 1_000,
      speedKph: 48,
      handling: 2,
      operatingCost: 420,
      consumption: 'high',
      imageKey: 'large_truck',
      strengthsKeys: ['vehicle.strength.capacity', 'vehicle.strength.long_routes'],
      weaknessesKeys: ['vehicle.weakness.slow', 'vehicle.weakness.cost'],
      loadTimeSec: 16,
      unloadTimeSecPerTarget: 6,
      narrowStreetPenalty: 0.28,
    },
    {
      id: 'refrigerated_truck',
      nameKey: 'vehicle.refrigerated_truck',
      descriptionKey: 'vehicle.refrigerated_truck.desc',
      unlockLevel: 8,
      capacity: 380,
      speedKph: 65,
      handling: 4,
      operatingCost: 310,
      consumption: 'medium',
      imageKey: 'refrigerated_truck',
      strengthsKeys: ['vehicle.strength.cooling', 'vehicle.strength.quality'],
      weaknessesKeys: ['vehicle.weakness.cost', 'vehicle.weakness.capacity'],
      loadTimeSec: 9,
      unloadTimeSecPerTarget: 5,
      narrowStreetPenalty: 0.12,
      cooling: true,
    },
    {
      id: 'heavy_transporter',
      nameKey: 'vehicle.heavy_transporter',
      descriptionKey: 'vehicle.heavy_transporter.desc',
      unlockLevel: 14,
      capacity: 1_600,
      speedKph: 38,
      handling: 1,
      operatingCost: 620,
      consumption: 'high',
      imageKey: 'heavy_transporter',
      strengthsKeys: ['vehicle.strength.special', 'vehicle.strength.capacity'],
      weaknessesKeys: ['vehicle.weakness.very_slow', 'vehicle.weakness.narrow'],
      loadTimeSec: 22,
      unloadTimeSecPerTarget: 7,
      narrowStreetPenalty: 0.4,
    },
    {
      id: 'flatbed',
      nameKey: 'vehicle.flatbed',
      descriptionKey: 'vehicle.flatbed.desc',
      unlockLevel: 7,
      capacity: 620,
      speedKph: 58,
      handling: 3,
      operatingCost: 280,
      consumption: 'medium',
      imageKey: 'truck_material',
      strengthsKeys: ['vehicle.strength.material', 'vehicle.strength.balance'],
      weaknessesKeys: ['vehicle.weakness.weather', 'vehicle.weakness.cost'],
      loadTimeSec: 12,
      unloadTimeSecPerTarget: 5,
      narrowStreetPenalty: 0.18,
    },
    {
      id: 'logging_truck',
      nameKey: 'vehicle.logging_truck',
      descriptionKey: 'vehicle.logging_truck.desc',
      unlockLevel: 8,
      capacity: 780,
      speedKph: 52,
      handling: 2,
      operatingCost: 340,
      consumption: 'high',
      imageKey: 'truck_material',
      strengthsKeys: ['vehicle.strength.wood', 'vehicle.strength.capacity'],
      weaknessesKeys: ['vehicle.weakness.narrow', 'vehicle.weakness.slow'],
      loadTimeSec: 14,
      unloadTimeSecPerTarget: 6,
      narrowStreetPenalty: 0.3,
    },
    {
      id: 'fire_truck',
      nameKey: 'vehicle.fire_truck',
      descriptionKey: 'vehicle.fire_truck.desc',
      unlockLevel: 9,
      capacity: 420,
      speedKph: 72,
      handling: 4,
      operatingCost: 360,
      consumption: 'high',
      imageKey: 'firetruck',
      strengthsKeys: ['vehicle.strength.priority', 'vehicle.strength.fast'],
      weaknessesKeys: ['vehicle.weakness.mission_only', 'vehicle.weakness.cost'],
      loadTimeSec: 4,
      unloadTimeSecPerTarget: 3,
      narrowStreetPenalty: 0.08,
    },
    {
      id: 'police_car',
      nameKey: 'vehicle.police_car',
      descriptionKey: 'vehicle.police_car.desc',
      unlockLevel: 11,
      capacity: 80,
      speedKph: 96,
      handling: 5,
      operatingCost: 210,
      consumption: 'medium',
      imageKey: 'police_car',
      strengthsKeys: ['vehicle.strength.fast', 'vehicle.strength.agile'],
      weaknessesKeys: ['vehicle.weakness.capacity', 'vehicle.weakness.mission_only'],
      loadTimeSec: 2,
      unloadTimeSecPerTarget: 2,
      narrowStreetPenalty: 0,
    },
    {
      id: 'freight_train',
      nameKey: 'vehicle.freight_train',
      descriptionKey: 'vehicle.freight_train.desc',
      unlockLevel: 18,
      capacity: 8_000,
      speedKph: 70,
      handling: 1,
      operatingCost: 1_200,
      consumption: 'medium',
      imageKey: 'freight_train',
      strengthsKeys: ['vehicle.strength.capacity', 'vehicle.strength.long_routes'],
      weaknessesKeys: ['vehicle.weakness.rail', 'vehicle.weakness.future'],
      future: true,
    },
    {
      id: 'cargo_plane',
      nameKey: 'vehicle.cargo_plane',
      descriptionKey: 'vehicle.cargo_plane.desc',
      unlockLevel: 20,
      capacity: 12_000,
      speedKph: 520,
      handling: 1,
      operatingCost: 3_800,
      consumption: 'high',
      imageKey: 'cargo_plane',
      strengthsKeys: ['vehicle.strength.fast', 'vehicle.strength.long_routes'],
      weaknessesKeys: ['vehicle.weakness.airport', 'vehicle.weakness.future'],
      future: true,
    },
  ],

  // -- Trade contracts (§ Handelsaufträge): rotating offers at the trading ----
  // post. Fulfilling consumes the demanded goods and pays out well above the
  // plain sell value — active trading beats dumping stock. Weights steer how
  // often a template shows; the mega contracts are deliberately rare.
  tradeContracts: [
    { id: 'wood_small', minLevel: 5, demands: { wood: 150 }, rewardMoney: 2_600, rewardXp: 8, weight: 3 },
    { id: 'stone_small', minLevel: 6, demands: { stone: 120 }, rewardMoney: 4_200, rewardXp: 10, weight: 3 },
    { id: 'food_small', minLevel: 6, demands: { food: 400 }, rewardMoney: 3_400, rewardXp: 8, weight: 3 },
    { id: 'wood_medium', minLevel: 8, demands: { wood: 600 }, rewardMoney: 11_000, rewardXp: 20, weight: 2 },
    { id: 'stone_medium', minLevel: 8, demands: { stone: 500 }, rewardMoney: 17_000, rewardXp: 22, weight: 2 },
    { id: 'mixed_medium', minLevel: 9, demands: { wood: 400, stone: 300, food: 600 }, rewardMoney: 21_000, rewardXp: 26, weight: 2 },
    { id: 'food_large', minLevel: 10, demands: { food: 2_500 }, rewardMoney: 24_000, rewardXp: 30 },
    { id: 'wood_large', minLevel: 10, demands: { wood: 1_500 }, rewardMoney: 28_000, rewardXp: 30 },
    { id: 'stone_large', minLevel: 11, demands: { stone: 1_200 }, rewardMoney: 42_000, rewardXp: 34 },
    { id: 'mixed_large', minLevel: 11, demands: { wood: 1_200, stone: 900, food: 1_500 }, rewardMoney: 60_000, rewardXp: 45 },
    { id: 'mega_export', minLevel: 10, demands: { wood: 2_500, stone: 1_800 }, rewardMoney: 250_000, rewardXp: 90, rewardGold: 5, weight: 0.5 },
    { id: 'mega_metropolis', minLevel: 12, demands: { wood: 4_000, stone: 3_000, food: 4_000 }, rewardMoney: 1_000_000, rewardXp: 200, rewardGold: 15, weight: 0.25 },
  ],
  tradeRotationSec: 30 * 60,
  tradeOffersPerRotation: 3,
  // § P2 (D-050): Selbstfahren zahlt 20 % mehr. Bewusst spürbar, aber kein
  // Zwang — wer die Stadt fahren lässt, verliert nichts, er gewinnt nur weniger.
  manualDriveBonusFactor: 1.2,
};
