import type { BuildingDef } from './types.ts';

export const buildingsConfig: BuildingDef[] = [
  // ---- Verwaltung / Regierung ----
  {
    id: 'town_hall',
    category: 'government',
    nameKey: 'building.town_hall',
    size: { w: 3, h: 3 },
    requiresRoad: false,
    unlockLevel: 1,
    cost: {},
    constructionSec: 0,
    xpReward: 0,
    unique: true,
    buildable: false,
    effects: [
      { type: 'jobs', amount: 5 },
      { type: 'storage', resource: 'wood', amount: 300 },
      { type: 'storage', resource: 'stone', amount: 300 },
      { type: 'storage', resource: 'food', amount: 300 },
    ],
  },
  {
    id: 'mayor_house',
    category: 'government',
    nameKey: 'building.mayor_house',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 3,
    cost: { money: 120, wood: 30 },
    constructionSec: 60,
    xpReward: 25,
    unique: true,
    effects: [],
  },

  // ---- Straßen ----
  {
    id: 'road',
    category: 'roads',
    nameKey: 'building.road',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 1,
    cost: { money: 5 },
    constructionSec: 0,
    xpReward: 1,
    effects: [],
  },

  // ---- Wohnen ----
  {
    id: 'house_small',
    category: 'residential',
    nameKey: 'building.house_small',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 1,
    cost: { money: 50, wood: 15 },
    constructionSec: 20,
    xpReward: 10,
    effects: [{ type: 'capacity', need: 'housing', amount: 6 }],
    upgrades: [
      {
        cost: { money: 120, wood: 30, stone: 10 },
        constructionSec: 60,
        xpReward: 15,
        effects: [{ type: 'capacity', need: 'housing', amount: 11 }],
      },
      {
        cost: { money: 300, wood: 60, stone: 40 },
        constructionSec: 180,
        xpReward: 25,
        effects: [{ type: 'capacity', need: 'housing', amount: 18 }],
      },
    ],
  },
  {
    id: 'house_row',
    category: 'residential',
    nameKey: 'building.house_row',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 6,
    cost: { money: 160, wood: 60, stone: 30 },
    constructionSec: 120,
    xpReward: 20,
    effects: [{ type: 'capacity', need: 'housing', amount: 14 }],
  },
  {
    id: 'apartment',
    category: 'residential',
    nameKey: 'building.apartment',
    size: { w: 2, h: 3 },
    requiresRoad: true,
    unlockLevel: 9,
    cost: { money: 450, wood: 100, stone: 140 },
    constructionSec: 360,
    xpReward: 45,
    effects: [{ type: 'capacity', need: 'housing', amount: 34 }],
  },

  // ---- Ressourcen / Produktion ----
  {
    id: 'sawmill',
    category: 'production',
    nameKey: 'building.sawmill',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 2,
    cost: { money: 80 },
    constructionSec: 30,
    xpReward: 12,
    effects: [
      { type: 'produce', resource: 'wood', perMinute: 9 },
      { type: 'jobs', amount: 4 },
      { type: 'ambience', amount: -1, radius: 4 },
    ],
    locationBonus: { terrain: 'forest', radius: 3, perTilePct: 5, maxPct: 50 },
  },
  {
    id: 'quarry',
    category: 'production',
    nameKey: 'building.quarry',
    size: { w: 3, h: 3 },
    requiresRoad: true,
    unlockLevel: 4,
    cost: { money: 140, wood: 50 },
    constructionSec: 90,
    xpReward: 18,
    effects: [
      { type: 'produce', resource: 'stone', perMinute: 6 },
      { type: 'jobs', amount: 6 },
      { type: 'ambience', amount: -2, radius: 5 },
    ],
    locationBonus: { terrain: 'mountain', radius: 3, perTilePct: 8, maxPct: 60 },
  },
  {
    id: 'farm',
    category: 'production',
    nameKey: 'building.farm',
    size: { w: 3, h: 3 },
    requiresRoad: true,
    unlockLevel: 4,
    cost: { money: 110, wood: 30 },
    constructionSec: 60,
    xpReward: 15,
    effects: [
      { type: 'produce', resource: 'food', perMinute: 10 },
      { type: 'jobs', amount: 4 },
    ],
    locationBonus: { terrain: 'fertile', radius: 2, perTilePct: 4, maxPct: 40 },
  },
  {
    id: 'well',
    category: 'services',
    nameKey: 'building.well',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 3,
    cost: { money: 40, wood: 5 },
    constructionSec: 15,
    xpReward: 8,
    effects: [{ type: 'capacity', need: 'water', amount: 25, radius: 7 }],
  },
  {
    id: 'water_pump',
    category: 'services',
    nameKey: 'building.water_pump',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 7,
    cost: { money: 260, stone: 60 },
    constructionSec: 180,
    xpReward: 28,
    effects: [
      { type: 'capacity', need: 'water', amount: 90, radius: 12 },
      { type: 'jobs', amount: 2 },
    ],
  },
  {
    id: 'warehouse',
    category: 'production',
    nameKey: 'building.warehouse',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 6,
    cost: { money: 200, wood: 60, stone: 30 },
    constructionSec: 120,
    xpReward: 22,
    effects: [
      { type: 'storage', resource: 'wood', amount: 200 },
      { type: 'storage', resource: 'stone', amount: 200 },
      { type: 'storage', resource: 'food', amount: 200 },
      { type: 'jobs', amount: 2 },
    ],
  },

  // ---- Versorgung ----
  {
    id: 'market',
    category: 'services',
    nameKey: 'building.market',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 5,
    cost: { money: 150, wood: 40 },
    constructionSec: 90,
    xpReward: 20,
    effects: [
      { type: 'distribution', need: 'food' },
      { type: 'jobs', amount: 6 },
    ],
  },
  {
    id: 'bakery',
    category: 'services',
    nameKey: 'building.bakery',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 9,
    cost: { money: 320, wood: 50, stone: 40 },
    constructionSec: 240,
    xpReward: 32,
    effects: [
      { type: 'produce', resource: 'food', perMinute: 6 },
      { type: 'jobs', amount: 4 },
    ],
  },
  {
    id: 'fire_station',
    category: 'services',
    nameKey: 'building.fire_station',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 8,
    cost: { money: 400, wood: 60, stone: 80 },
    constructionSec: 300,
    xpReward: 40,
    effects: [
      { type: 'protection', hazard: 'fire', radius: 12 },
      { type: 'jobs', amount: 6 },
    ],
  },

  // ---- Wirtschaft ----
  {
    id: 'shop_small',
    category: 'economy',
    nameKey: 'building.shop_small',
    size: { w: 2, h: 2 },
    requiresRoad: true,
    unlockLevel: 6,
    cost: { money: 220, wood: 40 },
    constructionSec: 150,
    xpReward: 24,
    effects: [
      { type: 'produce', resource: 'money', perMinute: 4 },
      { type: 'jobs', amount: 8 },
    ],
  },

  // ---- Freizeit ----
  {
    id: 'park',
    category: 'leisure',
    nameKey: 'building.park',
    size: { w: 2, h: 2 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 120, wood: 20 },
    constructionSec: 60,
    xpReward: 15,
    effects: [
      { type: 'coverage', need: 'leisure', radius: 8 },
      { type: 'ambience', amount: 2, radius: 6 },
    ],
  },
  {
    id: 'playground',
    category: 'leisure',
    nameKey: 'building.playground',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 60, wood: 15 },
    constructionSec: 30,
    xpReward: 8,
    effects: [
      { type: 'coverage', need: 'leisure', radius: 5 },
      { type: 'ambience', amount: 1, radius: 4 },
    ],
  },

  // ---- Dekoration ----
  {
    id: 'deco_tree',
    category: 'decoration',
    nameKey: 'building.deco_tree',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 10 },
    constructionSec: 0,
    xpReward: 1,
    effects: [{ type: 'ambience', amount: 1, radius: 3 }],
  },
  {
    id: 'deco_flowerbed',
    category: 'decoration',
    nameKey: 'building.deco_flowerbed',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 15 },
    constructionSec: 0,
    xpReward: 1,
    effects: [{ type: 'ambience', amount: 1, radius: 3 }],
  },
  {
    id: 'deco_fountain',
    category: 'decoration',
    nameKey: 'building.deco_fountain',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 80, stone: 10 },
    constructionSec: 20,
    xpReward: 3,
    effects: [{ type: 'ambience', amount: 2, radius: 4 }],
  },
  {
    id: 'deco_bench',
    category: 'decoration',
    nameKey: 'building.deco_bench',
    size: { w: 1, h: 1 },
    requiresRoad: false,
    unlockLevel: 7,
    cost: { money: 20, wood: 5 },
    constructionSec: 0,
    xpReward: 1,
    effects: [{ type: 'ambience', amount: 1, radius: 2 }],
  },
];
