import type { QuestDef } from './types.ts';

// Linear tutorial/build-up chain that carries the player through level 1–10.
// Quests activate when their unlockLevel is reached AND the previous quest in
// the chain is completed. Money rewards match the municipal scale (§4) and act
// as "city development grants" — with building costs raised (v0.8), these
// challenge grants are now the *rewarding* money source: active play (finishing
// objectives) funds the next expansion far better than passive AFK income.
export const questsConfig: QuestDef[] = [
  {
    id: 'q01_roads',
    sender: 'buildingDept',
    titleKey: 'quest.q01.title',
    descriptionKey: 'quest.q01.desc',
    unlockLevel: 1,
    objectives: [{ type: 'build', defId: 'road', count: 5 }],
    rewards: { money: 8_000, xp: 12 },
    nextQuestId: 'q02_houses',
  },
  {
    id: 'q02_houses',
    sender: 'citizen',
    titleKey: 'quest.q02.title',
    descriptionKey: 'quest.q02.desc',
    unlockLevel: 1,
    objectives: [{ type: 'build', defId: 'house_small', count: 2 }],
    rewards: { money: 16_000, xp: 18 },
    nextQuestId: 'q03_sawmill',
  },
  {
    id: 'q03_sawmill',
    sender: 'buildingDept',
    titleKey: 'quest.q03.title',
    descriptionKey: 'quest.q03.desc',
    unlockLevel: 2,
    objectives: [
      { type: 'build', defId: 'sawmill', count: 1 },
      { type: 'produce', resource: 'wood', amount: 30 },
    ],
    rewards: { money: 24_000, xp: 25 },
    nextQuestId: 'q04_water',
  },
  {
    id: 'q04_water',
    sender: 'citizen',
    titleKey: 'quest.q04.title',
    descriptionKey: 'quest.q04.desc',
    unlockLevel: 3,
    objectives: [{ type: 'build', defId: 'well', count: 2 }],
    rewards: { money: 24_000, xp: 25 },
    nextQuestId: 'q05_mayor',
  },
  {
    id: 'q05_mayor',
    sender: 'mayor',
    titleKey: 'quest.q05.title',
    descriptionKey: 'quest.q05.desc',
    unlockLevel: 3,
    objectives: [
      { type: 'build', defId: 'mayor_house', count: 1 },
      { type: 'mayorAction', actionId: 'speech', count: 1 },
    ],
    rewards: { money: 36_000, xp: 35 },
    nextQuestId: 'q06_food',
  },
  {
    id: 'q06_food',
    sender: 'citizen',
    titleKey: 'quest.q06.title',
    descriptionKey: 'quest.q06.desc',
    unlockLevel: 4,
    objectives: [
      { type: 'build', defId: 'farm', count: 1 },
      { type: 'produce', resource: 'food', amount: 50 },
    ],
    rewards: { money: 36_000, xp: 32 },
    nextQuestId: 'q07_stone',
  },
  {
    id: 'q07_stone',
    sender: 'buildingDept',
    titleKey: 'quest.q07.title',
    descriptionKey: 'quest.q07.desc',
    unlockLevel: 4,
    objectives: [
      { type: 'build', defId: 'quarry', count: 1 },
      { type: 'produce', resource: 'stone', amount: 40 },
    ],
    rewards: { money: 45_000, xp: 45 },
    nextQuestId: 'q08_market',
  },
  {
    id: 'q08_market',
    sender: 'merchant',
    titleKey: 'quest.q08.title',
    descriptionKey: 'quest.q08.desc',
    unlockLevel: 5,
    objectives: [
      { type: 'build', defId: 'market', count: 1 },
      { type: 'happiness', amount: 70 },
    ],
    rewards: { money: 70_000, xp: 60 },
    nextQuestId: 'q09_expand',
  },
  {
    id: 'q09_expand',
    sender: 'buildingDept',
    titleKey: 'quest.q09.title',
    descriptionKey: 'quest.q09.desc',
    unlockLevel: 5,
    objectives: [{ type: 'sectors', count: 2 }],
    rewards: { money: 95_000, xp: 75 },
    nextQuestId: 'q10_growth',
  },
  {
    id: 'q10_growth',
    sender: 'citizen',
    titleKey: 'quest.q10.title',
    descriptionKey: 'quest.q10.desc',
    unlockLevel: 5,
    objectives: [{ type: 'population', amount: 1_600 }],
    rewards: { money: 80_000, xp: 40 },
    nextQuestId: 'q11_economy',
  },
  {
    id: 'q11_economy',
    sender: 'merchant',
    titleKey: 'quest.q11.title',
    descriptionKey: 'quest.q11.desc',
    unlockLevel: 6,
    objectives: [
      { type: 'build', defId: 'shop_small', count: 2 },
      { type: 'build', defId: 'warehouse', count: 1 },
    ],
    rewards: { money: 130_000, xp: 95 },
    nextQuestId: 'q12_leisure',
  },
  {
    id: 'q12_leisure',
    sender: 'citizen',
    titleKey: 'quest.q12.title',
    descriptionKey: 'quest.q12.desc',
    unlockLevel: 7,
    objectives: [
      { type: 'build', defId: 'park', count: 1 },
      { type: 'build', defId: 'playground', count: 1 },
      { type: 'happiness', amount: 75 },
    ],
    rewards: { money: 160_000, xp: 120 },
    nextQuestId: 'q13_fire',
  },
  {
    id: 'q13_fire',
    sender: 'fire',
    titleKey: 'quest.q13.title',
    descriptionKey: 'quest.q13.desc',
    unlockLevel: 8,
    objectives: [{ type: 'build', defId: 'fire_station', count: 1 }],
    rewards: { money: 190_000, xp: 140 },
    nextQuestId: 'q14_density',
  },
  {
    id: 'q14_density',
    sender: 'citizen',
    titleKey: 'quest.q14.title',
    descriptionKey: 'quest.q14.desc',
    unlockLevel: 10,
    objectives: [
      { type: 'build', defId: 'apartment', count: 1 },
      { type: 'population', amount: 5_000 },
    ],
    rewards: { money: 280_000, xp: 190 },
    nextQuestId: 'q15_metropolis',
  },
  {
    id: 'q15_metropolis',
    sender: 'mayor',
    titleKey: 'quest.q15.title',
    descriptionKey: 'quest.q15.desc',
    unlockLevel: 10,
    objectives: [
      { type: 'sectors', count: 4 },
      { type: 'population', amount: 8_000 },
      { type: 'happiness', amount: 80 },
    ],
    rewards: { money: 550_000, gold: 50, xp: 340 },
    nextQuestId: 'q16_power',
  },
  // ---- MVP 2: energy grid ----
  {
    id: 'q16_power',
    sender: 'buildingDept',
    titleKey: 'quest.q16.title',
    descriptionKey: 'quest.q16.desc',
    unlockLevel: 11,
    objectives: [
      { type: 'build', defId: 'power_plant', count: 1 },
      { type: 'happiness', amount: 70 },
    ],
    rewards: { money: 380_000, xp: 260 },
    nextQuestId: 'q17_grid',
  },
  {
    id: 'q17_grid',
    sender: 'buildingDept',
    titleKey: 'quest.q17.title',
    descriptionKey: 'quest.q17.desc',
    unlockLevel: 12,
    objectives: [
      { type: 'build', defId: 'wind_farm', count: 1 },
      { type: 'population', amount: 11_000 },
    ],
    rewards: { money: 520_000, gold: 30, xp: 360 },
    nextQuestId: 'q18_safety',
  },
  // ---- MVP 2: emergency services ----
  {
    id: 'q18_safety',
    sender: 'fire',
    titleKey: 'quest.q18.title',
    descriptionKey: 'quest.q18.desc',
    unlockLevel: 13,
    objectives: [
      { type: 'build', defId: 'police_station', count: 1 },
      { type: 'happiness', amount: 72 },
    ],
    rewards: { money: 650_000, xp: 430 },
    nextQuestId: 'q19_health',
  },
  {
    id: 'q19_health',
    sender: 'citizen',
    titleKey: 'quest.q19.title',
    descriptionKey: 'quest.q19.desc',
    unlockLevel: 14,
    objectives: [
      { type: 'build', defId: 'hospital', count: 1 },
      { type: 'population', amount: 14_000 },
    ],
    rewards: { money: 850_000, gold: 40, xp: 560 },
  },

  // ---- Parallel early-game "side" quests (§6/§8/§9) --------------------------
  // These run ALONGSIDE the main chain (no predecessor, so each activates the
  // moment its level is reached) and reward active play with money/XP/gold so the
  // player always has a concrete goal instead of waiting for income. They lean on
  // the same objective types and are pure config — no bespoke quest code.
  {
    id: 'qe_wood',
    sender: 'merchant',
    titleKey: 'quest.qe_wood.title',
    descriptionKey: 'quest.qe_wood.desc',
    unlockLevel: 2,
    objectives: [{ type: 'produce', resource: 'wood', amount: 120 }],
    rewards: { money: 14_000, xp: 15 },
  },
  {
    id: 'qe_neighbours',
    sender: 'citizen',
    titleKey: 'quest.qe_neighbours.title',
    descriptionKey: 'quest.qe_neighbours.desc',
    unlockLevel: 3,
    objectives: [{ type: 'population', amount: 600 }],
    rewards: { money: 16_000, xp: 18 },
  },
  {
    id: 'qe_pantry',
    sender: 'citizen',
    titleKey: 'quest.qe_pantry.title',
    descriptionKey: 'quest.qe_pantry.desc',
    unlockLevel: 4,
    objectives: [{ type: 'produce', resource: 'food', amount: 150 }],
    rewards: { money: 20_000, xp: 18 },
  },
  {
    id: 'qe_stone',
    sender: 'buildingDept',
    titleKey: 'quest.qe_stone.title',
    descriptionKey: 'quest.qe_stone.desc',
    unlockLevel: 4,
    objectives: [{ type: 'produce', resource: 'stone', amount: 120 }],
    rewards: { money: 22_000, xp: 20 },
  },
  // Sector quests now count only ADDITIONAL sectors (§5): the free start sector
  // doesn't count, so "unlock your first new sector" means exactly one purchase.
  {
    id: 'qe_expand',
    sender: 'buildingDept',
    titleKey: 'quest.qe_expand.title',
    descriptionKey: 'quest.qe_expand.desc',
    unlockLevel: 5,
    objectives: [{ type: 'sectors', count: 1 }],
    rewards: { money: 40_000, gold: 10, xp: 30 },
  },
  {
    id: 'qe_expand3',
    sender: 'buildingDept',
    titleKey: 'quest.qe_expand3.title',
    descriptionKey: 'quest.qe_expand3.desc',
    unlockLevel: 7,
    objectives: [{ type: 'sectors', count: 3 }],
    rewards: { money: 110_000, xp: 70 },
  },
  {
    id: 'qe_expand4',
    sender: 'buildingDept',
    titleKey: 'quest.qe_expand4.title',
    descriptionKey: 'quest.qe_expand4.desc',
    unlockLevel: 9,
    objectives: [{ type: 'sectors', count: 4 }],
    rewards: { money: 180_000, xp: 110 },
  },
  {
    id: 'qe_happy',
    sender: 'citizen',
    titleKey: 'quest.qe_happy.title',
    descriptionKey: 'quest.qe_happy.desc',
    unlockLevel: 5,
    objectives: [{ type: 'happiness', amount: 80 }],
    rewards: { money: 45_000, gold: 10, xp: 35 },
  },
  // Level 7 housing drive (§16): "our city needs more homes". Its targets line up
  // with the residential build limits at L7 (house_small cap 10, house_row cap 6),
  // and — since `build` counts lifetime — it auto-completes for a player who has
  // already built that many. Pays out materials for the next expansion, too.
  {
    id: 'qe_housing',
    sender: 'buildingDept',
    titleKey: 'quest.qe_housing.title',
    descriptionKey: 'quest.qe_housing.desc',
    unlockLevel: 7,
    objectives: [
      { type: 'build', defId: 'house_small', count: 10 },
      { type: 'build', defId: 'house_row', count: 6 },
    ],
    rewards: { money: 120_000, xp: 90, resources: { wood: 200, stone: 120 } },
  },

  // ---- v0.21 active-play quests (§10–§14): Stadtarbeit, trade and upgrade
  // goals so levels 6–8 are things to DO, not income to wait for. All reuse the
  // generic objective types (activity / tradeEarnings / upgrade) — pure config.
  {
    id: 'qe_first_work',
    sender: 'mayor',
    titleKey: 'quest.qe_first_work.title',
    descriptionKey: 'quest.qe_first_work.desc',
    unlockLevel: 6,
    objectives: [{ type: 'activity', count: 1 }],
    rewards: { money: 18_000, xp: 30 },
  },
  {
    id: 'qe_first_trade',
    sender: 'merchant',
    titleKey: 'quest.qe_first_trade.title',
    descriptionKey: 'quest.qe_first_trade.desc',
    unlockLevel: 6,
    objectives: [{ type: 'tradeEarnings', amount: 10_000 }],
    rewards: { money: 22_000, xp: 35 },
  },
  {
    id: 'qe_rowhouses',
    sender: 'buildingDept',
    titleKey: 'quest.qe_rowhouses.title',
    descriptionKey: 'quest.qe_rowhouses.desc',
    unlockLevel: 6,
    objectives: [{ type: 'build', defId: 'house_row', count: 4 }],
    rewards: { money: 45_000, xp: 45 },
  },
  {
    id: 'qe_sawmill_up',
    sender: 'buildingDept',
    titleKey: 'quest.qe_sawmill_up.title',
    descriptionKey: 'quest.qe_sawmill_up.desc',
    unlockLevel: 7,
    objectives: [{ type: 'upgrade', defId: 'sawmill', count: 1 }],
    rewards: { money: 60_000, xp: 55 },
  },
  {
    id: 'qe_deliveries',
    sender: 'citizen',
    titleKey: 'quest.qe_deliveries.title',
    descriptionKey: 'quest.qe_deliveries.desc',
    unlockLevel: 7,
    objectives: [{ type: 'activity', count: 3 }],
    rewards: { money: 55_000, xp: 60 },
  },
  {
    id: 'qe_house_up',
    sender: 'citizen',
    titleKey: 'quest.qe_house_up.title',
    descriptionKey: 'quest.qe_house_up.desc',
    unlockLevel: 8,
    objectives: [{ type: 'upgrade', defId: 'house_small', count: 6 }],
    rewards: { money: 120_000, xp: 90 },
  },
  {
    id: 'qe_quarry_up',
    sender: 'buildingDept',
    titleKey: 'quest.qe_quarry_up.title',
    descriptionKey: 'quest.qe_quarry_up.desc',
    unlockLevel: 8,
    objectives: [{ type: 'upgrade', defId: 'quarry', count: 1 }],
    rewards: { money: 110_000, xp: 85 },
  },
  {
    id: 'qe_office',
    sender: 'merchant',
    titleKey: 'quest.qe_office.title',
    descriptionKey: 'quest.qe_office.desc',
    unlockLevel: 8,
    objectives: [{ type: 'build', defId: 'office', count: 1 }],
    rewards: { money: 130_000, xp: 95 },
  },
  {
    id: 'qe_big_trade',
    sender: 'merchant',
    titleKey: 'quest.qe_big_trade.title',
    descriptionKey: 'quest.qe_big_trade.desc',
    unlockLevel: 8,
    objectives: [{ type: 'tradeEarnings', amount: 150_000 }],
    rewards: { money: 90_000, gold: 10, xp: 80 },
  },
];
