import type { QuestDef } from './types.ts';

// Linear tutorial/build-up chain that carries the player through level 1–10.
// Quests activate when their unlockLevel is reached AND the previous quest in
// the chain is completed. Money rewards match the municipal scale (§4) and act
// as "city development grants" — a legible extra income source (§5).
export const questsConfig: QuestDef[] = [
  {
    id: 'q01_roads',
    titleKey: 'quest.q01.title',
    descriptionKey: 'quest.q01.desc',
    unlockLevel: 1,
    objectives: [{ type: 'build', defId: 'road', count: 5 }],
    rewards: { money: 6_000, xp: 5 },
    nextQuestId: 'q02_houses',
  },
  {
    id: 'q02_houses',
    titleKey: 'quest.q02.title',
    descriptionKey: 'quest.q02.desc',
    unlockLevel: 1,
    objectives: [{ type: 'build', defId: 'house_small', count: 2 }],
    rewards: { money: 10_000, xp: 10 },
    nextQuestId: 'q03_sawmill',
  },
  {
    id: 'q03_sawmill',
    titleKey: 'quest.q03.title',
    descriptionKey: 'quest.q03.desc',
    unlockLevel: 2,
    objectives: [
      { type: 'build', defId: 'sawmill', count: 1 },
      { type: 'produce', resource: 'wood', amount: 30 },
    ],
    rewards: { money: 14_000, xp: 15 },
    nextQuestId: 'q04_water',
  },
  {
    id: 'q04_water',
    titleKey: 'quest.q04.title',
    descriptionKey: 'quest.q04.desc',
    unlockLevel: 3,
    objectives: [{ type: 'build', defId: 'well', count: 2 }],
    rewards: { money: 14_000, xp: 15 },
    nextQuestId: 'q05_mayor',
  },
  {
    id: 'q05_mayor',
    titleKey: 'quest.q05.title',
    descriptionKey: 'quest.q05.desc',
    unlockLevel: 3,
    objectives: [
      { type: 'build', defId: 'mayor_house', count: 1 },
      { type: 'mayorAction', actionId: 'speech', count: 1 },
    ],
    rewards: { money: 20_000, xp: 20 },
    nextQuestId: 'q06_food',
  },
  {
    id: 'q06_food',
    titleKey: 'quest.q06.title',
    descriptionKey: 'quest.q06.desc',
    unlockLevel: 4,
    objectives: [
      { type: 'build', defId: 'farm', count: 1 },
      { type: 'produce', resource: 'food', amount: 50 },
    ],
    rewards: { money: 20_000, xp: 20 },
    nextQuestId: 'q07_stone',
  },
  {
    id: 'q07_stone',
    titleKey: 'quest.q07.title',
    descriptionKey: 'quest.q07.desc',
    unlockLevel: 4,
    objectives: [
      { type: 'build', defId: 'quarry', count: 1 },
      { type: 'produce', resource: 'stone', amount: 40 },
    ],
    rewards: { money: 24_000, xp: 25 },
    nextQuestId: 'q08_market',
  },
  {
    id: 'q08_market',
    titleKey: 'quest.q08.title',
    descriptionKey: 'quest.q08.desc',
    unlockLevel: 5,
    objectives: [
      { type: 'build', defId: 'market', count: 1 },
      { type: 'happiness', amount: 70 },
    ],
    rewards: { money: 35_000, xp: 30 },
    nextQuestId: 'q09_expand',
  },
  {
    id: 'q09_expand',
    titleKey: 'quest.q09.title',
    descriptionKey: 'quest.q09.desc',
    unlockLevel: 5,
    objectives: [{ type: 'sectors', count: 2 }],
    rewards: { money: 45_000, xp: 40 },
    nextQuestId: 'q10_growth',
  },
  {
    id: 'q10_growth',
    titleKey: 'quest.q10.title',
    descriptionKey: 'quest.q10.desc',
    unlockLevel: 5,
    objectives: [{ type: 'population', amount: 80 }],
    rewards: { money: 45_000, xp: 40 },
    nextQuestId: 'q11_economy',
  },
  {
    id: 'q11_economy',
    titleKey: 'quest.q11.title',
    descriptionKey: 'quest.q11.desc',
    unlockLevel: 6,
    objectives: [
      { type: 'build', defId: 'shop_small', count: 2 },
      { type: 'build', defId: 'warehouse', count: 1 },
    ],
    rewards: { money: 55_000, xp: 45 },
    nextQuestId: 'q12_leisure',
  },
  {
    id: 'q12_leisure',
    titleKey: 'quest.q12.title',
    descriptionKey: 'quest.q12.desc',
    unlockLevel: 7,
    objectives: [
      { type: 'build', defId: 'park', count: 1 },
      { type: 'build', defId: 'playground', count: 1 },
      { type: 'happiness', amount: 75 },
    ],
    rewards: { money: 65_000, xp: 50 },
    nextQuestId: 'q13_fire',
  },
  {
    id: 'q13_fire',
    titleKey: 'quest.q13.title',
    descriptionKey: 'quest.q13.desc',
    unlockLevel: 8,
    objectives: [{ type: 'build', defId: 'fire_station', count: 1 }],
    rewards: { money: 70_000, xp: 55 },
    nextQuestId: 'q14_density',
  },
  {
    id: 'q14_density',
    titleKey: 'quest.q14.title',
    descriptionKey: 'quest.q14.desc',
    unlockLevel: 9,
    objectives: [
      { type: 'build', defId: 'apartment', count: 1 },
      { type: 'population', amount: 250 },
    ],
    rewards: { money: 95_000, xp: 70 },
    nextQuestId: 'q15_metropolis',
  },
  {
    id: 'q15_metropolis',
    titleKey: 'quest.q15.title',
    descriptionKey: 'quest.q15.desc',
    unlockLevel: 10,
    objectives: [
      { type: 'sectors', count: 4 },
      { type: 'population', amount: 400 },
      { type: 'happiness', amount: 80 },
    ],
    rewards: { money: 250_000, gold: 50, xp: 100 },
  },
];
